"""Fixtures for warehouse tests.

Every test that touches the database gets its **own throwaway database**,
created and dropped around it. That is heavier than wrapping each test in a
rolled-back transaction, and it is worth it here for two reasons: migrations
contain their own transactions and DDL, so an outer transaction would not
isolate them cleanly; and a developer's locally loaded extract must never be
truncated by running the test suite.

Tests are skipped, loudly, when no Postgres is reachable. CI runs them against
a service container, so a skip there means something is wrong — hence `-rs` in
the CI invocation.
"""

from __future__ import annotations

import os
import uuid
from collections.abc import Iterator
from datetime import date
from pathlib import Path

import psycopg
import pytest
from psycopg import conninfo

from intus_warehouse import db
from intus_warehouse.migrate import run


def pytest_collection_modifyitems(config, items):
    """Mark every test in this suite as needing a database.

    Applied centrally rather than by decorating each test, so a new test cannot
    forget the marker and appear to pass on a machine with no Postgres.
    """
    for item in items:
        item.add_marker(pytest.mark.db)


@pytest.fixture(scope="session")
def _base_conninfo() -> dict[str, str]:
    if not db.is_available():
        pytest.skip(f"no Postgres reachable at {db.dsn()} — run `make up`")
    return conninfo.conninfo_to_dict(db.dsn())


@pytest.fixture(scope="session")
def _admin_dsn(_base_conninfo) -> str:
    """A connection to `postgres`, used only to create and drop test databases."""
    return conninfo.make_conninfo(**{**_base_conninfo, "dbname": "postgres"})


@pytest.fixture
def blank_database(_base_conninfo, _admin_dsn) -> Iterator[str]:
    """An empty database, dropped when the test finishes.

    The name carries a uuid so a crashed run cannot collide with the next one.
    """
    name = f"intus_test_{uuid.uuid4().hex[:12]}"
    with psycopg.connect(_admin_dsn, autocommit=True) as admin:
        admin.execute(f'CREATE DATABASE "{name}"')

    target = conninfo.make_conninfo(**{**_base_conninfo, "dbname": name})
    previous = os.environ.get(db.DSN_ENV_VAR)
    # Point the library's own DSN resolution at the throwaway database, so code
    # under test that calls db.connect() reaches the right place.
    os.environ[db.DSN_ENV_VAR] = target
    try:
        yield target
    finally:
        if previous is None:
            os.environ.pop(db.DSN_ENV_VAR, None)
        else:
            os.environ[db.DSN_ENV_VAR] = previous
        with psycopg.connect(_admin_dsn, autocommit=True) as admin:
            # FORCE terminates any connection the test left open; without it a
            # leaked connection turns cleanup into a hang.
            admin.execute(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)')


@pytest.fixture
def blank_connection(blank_database) -> Iterator[psycopg.Connection]:
    with psycopg.connect(blank_database) as connection:
        yield connection


@pytest.fixture
def migrated_connection(blank_connection) -> psycopg.Connection:
    """A database with the full migration set applied."""
    run(blank_connection)
    blank_connection.commit()
    return blank_connection


@pytest.fixture(scope="session")
def extract(tmp_path_factory) -> Path:
    """A small generated extract, produced once for the whole session.

    Generated by the real generators rather than hand-written CSV: the loader's
    contract is with the files `intus_gen` actually emits, and a hand-made
    fixture would drift from them silently.
    """
    from intus_gen.cli import main

    directory = tmp_path_factory.mktemp("extract")
    assert (
        main(
            [
                "generate",
                "--scale",
                "small",
                "--seed",
                "31337",
                "--as-of",
                date(2026, 6, 30).isoformat(),
                "--out",
                str(directory),
            ]
        )
        == 0
    )
    return directory
