-- The fact half of the star schema, plus the machinery facts need that
-- dimensions did not: a way to resolve a type-2 dimension key as of a point
-- in time, and an "unknown member" row in every dimension for the FK a fact
-- cannot otherwise resolve.

-- --------------------------------------------------------------------------
-- Point-in-time dimension lookup
-- --------------------------------------------------------------------------

-- The standard SCD2 fact-load join: which version of this employee was in
-- force on this date? A plain equi-join on employee_id would return every
-- version — up to a dozen rows for one AI-usage event — silently multiplying
-- every fact that joins to dim_employee. This is the one join every fact
-- against dim_employee needs, so it is written once.
--
-- Returns NULL, deliberately, when no version covers the date: either the
-- employee_id does not exist at all, or the date falls in a gap left by a
-- rejected span, or — the interesting case — the date is after the person's
-- last version closed. That NULL is not a bug to guard against; the
-- SEC_LOGIN_AFTER_TERMINATION rule below is built on exactly this function
-- returning NULL for an event dated after termination.
CREATE OR REPLACE FUNCTION warehouse.employee_key_as_of(p_employee_id text, p_as_of date)
RETURNS bigint
LANGUAGE sql STABLE AS $$
    SELECT employee_key
    FROM warehouse.dim_employee
    WHERE employee_id = p_employee_id
      AND p_as_of >= valid_from
      AND (valid_to IS NULL OR p_as_of < valid_to)
    LIMIT 1
$$;

COMMENT ON FUNCTION warehouse.employee_key_as_of IS
    'The employee_key in force on a given date, or NULL if no version covers it.';

-- The forgiving counterpart, for facts that need "who did this" rather than
-- "who was in this role that specific day". Point-in-time resolution fails
-- for a reason that is not a data-quality problem at all whenever the event
-- predates the person's earliest known version — a budget approved_date is
-- set to the prior November for every period, which is routinely before a
-- newer approver's first HR record. Falling all the way back to "Unknown"
-- for that case would be wrong: the person is known, just not as of that
-- exact day.
--
-- Deliberately not used by any dq_exception detection query — those need the
-- strict, gap-revealing behaviour of employee_key_as_of. This function is
-- only for the value actually stored in a fact row, where the best-known
-- identity beats a technically-correct NULL.
CREATE OR REPLACE FUNCTION warehouse.employee_key_best(p_employee_id text, p_as_of date)
RETURNS bigint
LANGUAGE sql STABLE AS $$
    SELECT coalesce(
        warehouse.employee_key_as_of(p_employee_id, p_as_of),
        (
            SELECT employee_key FROM warehouse.dim_employee
            WHERE employee_id = p_employee_id
            ORDER BY valid_from DESC
            LIMIT 1
        )
    )
$$;

COMMENT ON FUNCTION warehouse.employee_key_best IS
    'employee_key_as_of, falling back to the nearest known version instead of NULL.';

-- --------------------------------------------------------------------------
-- Unknown members
-- --------------------------------------------------------------------------

-- One sentinel row per dimension, key -1, for a fact whose foreign key does
-- not resolve to anything real but whose row still belongs in the warehouse.
-- The alternative — leaving the column NULL — pushes the problem onto every
-- report ever written against the fact: every join becomes a LEFT JOIN, and
-- every aggregate needs its own COALESCE or it silently drops the row from
-- a GROUP BY. An unknown member absorbs that once, here, instead of in every
-- downstream query.
--
-- Explicit keys (GENERATED BY DEFAULT, not ALWAYS) are exactly what makes
-- this insertable at all — a fixed, memorable id rather than whatever the
-- sequence happened to be at when this migration first ran.
INSERT INTO warehouse.dim_department (department_key, department_code, department_name, cost_center)
VALUES (-1, 'UNKNOWN', 'Unknown Department', NULL)
ON CONFLICT (department_key) DO NOTHING;

INSERT INTO warehouse.dim_employee (
    employee_key, employee_id, valid_from, valid_to, is_current, full_name
)
VALUES (-1, 'UNKNOWN', DATE '1900-01-01', NULL, true, 'Unknown Employee')
ON CONFLICT (employee_key) DO NOTHING;

INSERT INTO warehouse.dim_account (account_key, account_id, account_name, is_active)
VALUES (-1, 'UNKNOWN', 'Unknown Account', false)
ON CONFLICT (account_key) DO NOTHING;

INSERT INTO warehouse.dim_product (product_key, product_code, product_name)
VALUES (-1, 'UNKNOWN', 'Unknown Product')
ON CONFLICT (product_key) DO NOTHING;

-- --------------------------------------------------------------------------
-- Fact tables
-- --------------------------------------------------------------------------

-- Every foreign key below is DEFERRABLE INITIALLY DEFERRED, and it is not a
-- defensive habit — a real run failed without it. The transform runs
-- dimensions before facts in one transaction (30_dim_employee before
-- 60_fact_compensation, etc.), and dim_employee's reconciliation step
-- deletes any employee version the new extract no longer carries. The
-- moment that DELETE runs, the *previous* run's fact rows — not yet
-- truncated, since their own transform step hasn't run yet this transaction
-- — can still hold exactly the employee_key being removed, and an immediate
-- (the default) constraint raises ForeignKeyViolation mid-transaction over
-- a state that was always going to be corrected two steps later. Deferring
-- the check to COMMIT is what lets "delete the parent, then rebuild the
-- child" work at all within a single transaction; by commit time every fact
-- has been truncated and reloaded against the current dimensions, and
-- referential integrity holds.
CREATE TABLE IF NOT EXISTS warehouse.fact_compensation (
    compensation_id     text PRIMARY KEY,
    employee_key        bigint NOT NULL REFERENCES warehouse.dim_employee (employee_key) DEFERRABLE INITIALLY DEFERRED,
    date_key            integer NOT NULL REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    pay_grade           text,
    annual_salary_usd   numeric(12, 2),
    bonus_target_pct    numeric(5, 4),
    equity_units        integer,
    currency            text,
    change_reason       text
);

CREATE INDEX IF NOT EXISTS ix_fact_compensation_employee ON warehouse.fact_compensation (employee_key);

-- --------------------------------------------------------------------------
-- fact_performance_review
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.fact_performance_review (
    review_id              text PRIMARY KEY,
    employee_key           bigint NOT NULL REFERENCES warehouse.dim_employee (employee_key) DEFERRABLE INITIALLY DEFERRED,
    reviewer_employee_key  bigint REFERENCES warehouse.dim_employee (employee_key) DEFERRABLE INITIALLY DEFERRED,
    date_key               integer NOT NULL REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    review_period          text,
    rating                 smallint,
    rating_label            text,
    promotion_recommended  boolean
);

CREATE INDEX IF NOT EXISTS ix_fact_performance_review_employee
    ON warehouse.fact_performance_review (employee_key);

-- --------------------------------------------------------------------------
-- fact_subscription
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.fact_subscription (
    subscription_id     text PRIMARY KEY,
    account_key         bigint NOT NULL REFERENCES warehouse.dim_account (account_key) DEFERRABLE INITIALLY DEFERRED,
    product_key         bigint NOT NULL REFERENCES warehouse.dim_product (product_key) DEFERRABLE INITIALLY DEFERRED,
    start_date_key      integer NOT NULL REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    end_date_key        integer REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    seats               integer,
    arr_usd             numeric(12, 2),
    billing_frequency   text
);

CREATE INDEX IF NOT EXISTS ix_fact_subscription_account ON warehouse.fact_subscription (account_key);

-- --------------------------------------------------------------------------
-- fact_invoice
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.fact_invoice (
    invoice_id        text PRIMARY KEY,
    account_key       bigint NOT NULL REFERENCES warehouse.dim_account (account_key) DEFERRABLE INITIALLY DEFERRED,
    -- Deliberately a degenerate reference (plain text), not a foreign key to
    -- fact_subscription: two facts referencing each other by surrogate key is
    -- how a star schema turns into a graph. The subscription's natural key is
    -- enough to join when needed.
    subscription_id   text,
    issue_date_key    integer NOT NULL REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    due_date_key      integer NOT NULL REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    paid_date_key     integer REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    amount_usd        numeric(12, 2),
    currency          text,
    status            text
);

CREATE INDEX IF NOT EXISTS ix_fact_invoice_account ON warehouse.fact_invoice (account_key);
CREATE INDEX IF NOT EXISTS ix_fact_invoice_subscription ON warehouse.fact_invoice (subscription_id);

-- --------------------------------------------------------------------------
-- fact_opportunity
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.fact_opportunity (
    opportunity_id     text PRIMARY KEY,
    account_key        bigint NOT NULL REFERENCES warehouse.dim_account (account_key) DEFERRABLE INITIALLY DEFERRED,
    owner_employee_key bigint NOT NULL REFERENCES warehouse.dim_employee (employee_key) DEFERRABLE INITIALLY DEFERRED,
    product_key        bigint NOT NULL REFERENCES warehouse.dim_product (product_key) DEFERRABLE INITIALLY DEFERRED,
    created_date_key   integer NOT NULL REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    close_date_key     integer REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    opportunity_type   text,
    stage              text,
    amount_usd         numeric(12, 2),
    probability_pct    smallint,
    is_won             boolean
);

CREATE INDEX IF NOT EXISTS ix_fact_opportunity_account ON warehouse.fact_opportunity (account_key);
CREATE INDEX IF NOT EXISTS ix_fact_opportunity_owner ON warehouse.fact_opportunity (owner_employee_key);

-- --------------------------------------------------------------------------
-- fact_usage_daily
-- --------------------------------------------------------------------------

-- No surrogate primary key: the grain (one row per date/account/product) is
-- its own natural key, and nothing downstream references an individual usage
-- row. That absence is also what makes truncate-and-reload safe for this
-- table — see the transform file for the fuller argument.
CREATE TABLE IF NOT EXISTS warehouse.fact_usage_daily (
    date_key         integer NOT NULL REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    account_key      bigint NOT NULL REFERENCES warehouse.dim_account (account_key) DEFERRABLE INITIALLY DEFERRED,
    product_key      bigint NOT NULL REFERENCES warehouse.dim_product (product_key) DEFERRABLE INITIALLY DEFERRED,
    active_users     integer,
    sessions         integer,
    api_calls        integer,
    storage_gb       numeric(12, 3),
    avg_latency_ms   integer,
    error_count      integer
);

CREATE INDEX IF NOT EXISTS ix_fact_usage_daily_account ON warehouse.fact_usage_daily (account_key, date_key);
CREATE INDEX IF NOT EXISTS ix_fact_usage_daily_date ON warehouse.fact_usage_daily (date_key);

-- --------------------------------------------------------------------------
-- fact_ai_usage
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.fact_ai_usage (
    event_id            text PRIMARY KEY,
    -- Kept alongside employee_key deliberately: a fact whose FK resolution
    -- can fall back to the unknown member (-1) still needs the raw actor
    -- recoverable for investigation, without relying on a dimension join
    -- that was, by construction, unable to resolve it.
    employee_id         text NOT NULL,
    employee_key        bigint NOT NULL REFERENCES warehouse.dim_employee (employee_key) DEFERRABLE INITIALLY DEFERRED,
    department_key      bigint NOT NULL REFERENCES warehouse.dim_department (department_key) DEFERRABLE INITIALLY DEFERRED,
    date_key            integer NOT NULL REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    event_ts            timestamp NOT NULL,
    model                text,
    feature              text,
    prompt_tokens        integer,
    completion_tokens    integer,
    cost_usd             numeric(14, 6),
    latency_ms           integer,
    flagged_by_policy    boolean
);

CREATE INDEX IF NOT EXISTS ix_fact_ai_usage_employee ON warehouse.fact_ai_usage (employee_key);
CREATE INDEX IF NOT EXISTS ix_fact_ai_usage_date ON warehouse.fact_ai_usage (date_key);

-- --------------------------------------------------------------------------
-- fact_access_event
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.fact_access_event (
    event_id          text PRIMARY KEY,
    employee_id       text,  -- nullable: SEC_MISSING_ACTOR means there is none
    employee_key      bigint NOT NULL REFERENCES warehouse.dim_employee (employee_key) DEFERRABLE INITIALLY DEFERRED,
    department_key    bigint NOT NULL REFERENCES warehouse.dim_department (department_key) DEFERRABLE INITIALLY DEFERRED,
    date_key          integer NOT NULL REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    event_ts          timestamp NOT NULL,
    system            text,
    action            text,
    resource          text,
    source_ip         text,
    source_country    text,
    result            text,
    mfa_used          boolean
);

CREATE INDEX IF NOT EXISTS ix_fact_access_event_employee ON warehouse.fact_access_event (employee_key);
CREATE INDEX IF NOT EXISTS ix_fact_access_event_date ON warehouse.fact_access_event (date_key);

-- --------------------------------------------------------------------------
-- fact_gl_actual
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.fact_gl_actual (
    actual_id                text PRIMARY KEY,
    department_key           bigint NOT NULL REFERENCES warehouse.dim_department (department_key) DEFERRABLE INITIALLY DEFERRED,
    date_key                 integer NOT NULL REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED,
    -- Degenerate: the finance business key for the accounting period, not
    -- derivable from date_key alone in the general case (a fiscal calendar
    -- with a non-January year end would make the two disagree by design).
    fiscal_period            text,
    gl_account               text,
    gl_account_name          text,
    amount_usd               numeric(14, 2),
    vendor                   text,
    description              text,
    posted_by_employee_key   bigint NOT NULL REFERENCES warehouse.dim_employee (employee_key) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS ix_fact_gl_actual_department ON warehouse.fact_gl_actual (department_key, fiscal_period);

-- --------------------------------------------------------------------------
-- fact_budget
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.fact_budget (
    budget_id                 text PRIMARY KEY,
    department_key            bigint NOT NULL REFERENCES warehouse.dim_department (department_key) DEFERRABLE INITIALLY DEFERRED,
    fiscal_period             text,
    fiscal_year               smallint,
    fiscal_quarter            smallint,
    gl_account                text,
    gl_account_name           text,
    budget_usd                numeric(14, 2),
    approved_by_employee_key  bigint NOT NULL REFERENCES warehouse.dim_employee (employee_key) DEFERRABLE INITIALLY DEFERRED,
    approved_date_key         integer REFERENCES warehouse.dim_date (date_key) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS ix_fact_budget_department ON warehouse.fact_budget (department_key, fiscal_period);
